package com.juhe.pockettools.constelltion;

public class q {
	public String A = "";
	public String B = "";
	public String C = "";
	public String D = "";
	public String E = "";
	public String F = "";
	public boolean G = false;
	public String H = "";
	public String I = "";
	public String J = "";
	public String K = "";
	public String L = "";
	public String M = "";
	public String N = "";
	public String O = "";
	public String P;
	public String Q = "";
	public boolean R = false;
	public String S = "";
	public String T = "";
	public String U = "";
	public String V = "";
	public String W = "";
	public String X = "";
	public String Y = "";
	public String Z = "";
	public String a = "";
	public String aa = "";
	public String ab = "";
	public String b = "";
	public int c = 0;
	public boolean d = false;
	public String e = "";
	public String f = "";
	public String g = "";
	public String h = "";
	public int i = 0;
	public int j = 0;
	public int k = 0;
	public int l = 0;
	public String m = "";
	public boolean n = false;
	public String o = "";
	public String p = "";
	public String q = "";
	public String r = "";
	public int s = 0;
	public int t = 0;
	public int u = 0;
	public int v = 0;
	public String w = "";
	public boolean x = false;
	public String y = "";
	public String z = "";
}
